// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkUtwNxrM8qgnA4ynPQNmVeFgiu1gV2i0',
    appId: '1:67363314491:web:fd2ca186dabbda7a99351e',
    messagingSenderId: '67363314491',
    projectId: 'proyectociclista-6e820',
    authDomain: 'proyectociclista-6e820.firebaseapp.com',
    storageBucket: 'proyectociclista-6e820.appspot.com',
    measurementId: 'G-SRNDNLDQ6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASFK4C9Dl7Mua425SlJdn0SgKjaNdHHzE',
    appId: '1:67363314491:android:067715bc7f42ecf999351e',
    messagingSenderId: '67363314491',
    projectId: 'proyectociclista-6e820',
    storageBucket: 'proyectociclista-6e820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWtzBYHbZ_9-Etouyo3-XjcNxfezQjqw',
    appId: '1:67363314491:ios:a58bffa4df5d187499351e',
    messagingSenderId: '67363314491',
    projectId: 'proyectociclista-6e820',
    storageBucket: 'proyectociclista-6e820.appspot.com',
    iosClientId: '67363314491-ificase877lmibjo8s1nuhdrn5hvd2oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoCiclista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWtzBYHbZ_9-Etouyo3-XjcNxfezQjqw',
    appId: '1:67363314491:ios:a58bffa4df5d187499351e',
    messagingSenderId: '67363314491',
    projectId: 'proyectociclista-6e820',
    storageBucket: 'proyectociclista-6e820.appspot.com',
    iosClientId: '67363314491-ificase877lmibjo8s1nuhdrn5hvd2oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoCiclista',
  );
}
